# Generated by Django 5.0.7 on 2024-08-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_book_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='speciality',
        ),
        migrations.AddField(
            model_name='book',
            name='sp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.speciality'),
        ),
    ]
